---

- name: create and add new disk(s) to vmware vm
  hosts: 192.168.100.63
  strategy: debug
  gather_facts: yes
  vars:
    vcenter_server: vcsa67.rtp.raleigh.ibm.com
    vcenter_user: "administrator@vsphere.local"
    vcenter_pass: Termin8t3r!!
    datacenter: "dc01"
    cluster: "cluster01"
    datastore: "dc01-ds01"
    ansible_ssh_pass: password
    become_user: root

  tasks:
  - name: get VM info
    vmware_guest_disk_facts:
      hostname: "{{ vcenter_server }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: False
      datacenter: "{{ datacenter }}"
      name: "{{ vmname }}"
    delegate_to: localhost
    register: vm_disk_info

  - name: add disk
    vmware_guest_disk:
      hostname: "{{ vcenter_server }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: False
      datacenter: "{{ datacenter }}"
      name: "{{ vmname }}"
      disk:
        - size_gb: "{{ disksize }}"
          type: thin
          state: present
          datastore: "{{ datastore }}"
          # autoselect_datastore: True
          scsi_controller: 1
          unit_number: 2
          scsi_type: 'paravirtual'
    delegate_to: localhost
    register: add_disk

  - name: List the files
    command: "hostname -f"
    ignore_errors: yes
    register: results
    

  - debug: var=results.stdout

  - name: List the files
    shell: "ls -la"
    ignore_errors: yes
    register: results1

  - debug: var=results1.stdout

#  - name: Create the file
#    file: path="{{ remote_file_path }}" state=touch mode=755

#  - name: Check remote file path
#    stat: path="{{remote_file_path}}"
#    register: file_path

#  - name: file content
#    set_fact: file_content="pvcreate /dev/sdb; vgextend centos /dev/sdb; lvextend -l +100%FREE /dev/centos/root -r"

#  - name: copy content
#    copy: content="{{file_content}}" dest="{{remote_file_path}}"
#    when: file_path.stat.exists == true

  - name: execute the script
    command: pvcreate /dev/sdb; vgextend centos /dev/sdb; lvextend -l +100%FREE /dev/centos/root -r
  