---

- name: create and add new disk(s) to vmware vm
  hosts: localhost
  strategy: debug
  gather_facts: yes
  vars:
    vcenter_server: vcsa67.rtp.raleigh.ibm.com
    vcenter_user: "administrator@vsphere.local"
    vcenter_pass: Termin8t3r!!
    datacenter: "dc01"
    cluster: "cluster01"
    datastore: "dc01-ds01"
    ansible_ssh_pass: Passw0rd
    become_user: root

  tasks:
  - name: get VM info
    vmware_guest_disk_facts:
      hostname: "{{ vcenter_server }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: False
      datacenter: "{{ datacenter }}"
      name: "{{ vmname }}"
    delegate_to: localhost
    register: vm_disk_info

  - name: add disk
    vmware_guest_disk:
      hostname: "{{ vcenter_server }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: False
      datacenter: "{{ datacenter }}"
      name: "{{ vmname }}"
      disk:
        - size_gb: "{{ disksize }}"
          type: thin
          state: present
          datastore: "{{ datastore }}"
          # autoselect_datastore: True
          scsi_controller: 1
          unit_number: 2
          scsi_type: 'paravirtual'
    delegate_to: localhost
    register: add_disk

  - name: List the files
    command: "ls -la /"
    register: list

  - debug: var=result.stdout_lines

  - name: Resize the disk 
    cmd: "pvcreate /deb/sdb; vgextend centos /deb/sdb; lvextend -l +100% FREE /dev/centos/root -r"
    register: result

  - debug: var=result.stdout_lines

      
    