---

- name: create and add new disk(s) to vmware vm
  hosts: localhost
  strategy: debug
  gather_facts: yes
  vars:
    vcenter_server: vcsa67.rtp.raleigh.ibm.com
    vcenter_user: "administrator@vsphere.local"
    vcenter_pass: Termin8t3r!!
    datacenter: "dc01"
    cluster: "cluster01"
    datastore: "dc01-ds01"

  tasks:
  - name: get VM info
    vmware_guest_disk_facts:
      hostname: "{{ vcenter_server }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: False
      datacenter: "{{ datacenter }}"
      name: "{{ vmname }}"
    delegate_to: localhost
    register: vm_disk_info
    
  - debug: 
      msg: vm_disk_info