---
- hosts: localhost
  gather_facts: no
  vars:
    vcenter_server: vcsa67.rtp.raleigh.ibm.com
    vcenter_user: "administrator@vsphere.local"
    vcenter_pass: Termin8t3r!!
    datacenter: "dc01"
    cluster: "cluster01"
    
  tasks:
    - name: Clone the template
      vmware_guest:
        hostname: "{{ vcenter_server }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        template: "centos7-template"
        validate_certs: False
        name: "{{ vmname }}"
        datacenter: "{{ datacenter }}"
        cluster: "{{ cluster }}"
        folder: "/{{ datacenter }}/vm/webb-cloudforms"
        datastore: "dc01-ds01"
        state: poweredon
        wait_for_ip_address: yes
      delegate_to: localhost
 
    
